version: '3.1'

services:
  db:
    image: postgres:16.0
    restart: always
    environment:
     - POSTGRES_PASSWORD=test
     - POSTGRES_USER=test
     - POSTGRES_DB=test
    ports:
      - "5432:5432"
  pg:
    depends_on:
      - db
    image: dpage/pgadmin4
    environment:
     - PGADMIN_DEFAULT_EMAIL=dev@dev.dev
     - PGADMIN_DEFAULT_PASSWORD=t
    ports:
      - "8081:80"
    volumes:
      - ./servers.json:/pgadmin4/servers.json
